spring.mongodb.uri=mongodb+srv://healthapp:healthapp@healthcluster.m3q7tys.mongodb.net/healthapp?retryWrites=true&w=majority
spring.mongodb.database=healthapp

spring.application.name=healthapp
server.port=8080

healthapp.jwt.secret=MiClaveSecretaSuperSeguraParaJWT2420!!
healthapp.jwt.expiration=3600000
